### ISSUE TITLE
Handle timeout

### ISSUE THREAD

**Issue by RoySegall** [hasadna/open-pension-logger#1]
For some reason I'm getting this:

```
/home/app/node_modules/elasticsearch/src/lib/transport.js:429
monthly_1                |       cb();
monthly_1                |       ^
monthly_1                | Error: Request Timeout after 30000ms
monthly_1                |     at /home/app/node_modules/elasticsearch/src/lib/transport.js:397:9
monthly_1                |     at Timeout.<anonymous> (/home/app/node_modules/elasticsearch/src/lib/transport.js:429:7)
monthly_1                |     at listOnTimeout (node:internal/timers:557:17)
monthly_1                |     at processTimers (node:internal/timers:500:7)
````

This one kills the services and cause a coupe of issues.

**Comment by RoySegall** [comment]
https://www.elastic.co/blog/new-elasticsearch-javascript-client-released
